#!/usr/bin/env python3
import argparse
import os
import subprocess
from collections import defaultdict


def parse_required(path):
    required = defaultdict(list)
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) != 2:
                continue
            lib, sym = parts
            required[lib].append(sym)
    return required


def nm_symbols(nm_path, so_path):
    try:
        output = subprocess.check_output(
            [nm_path, "-D", "--defined-only", so_path],
            stderr=subprocess.DEVNULL,
            text=True,
            errors="ignore",
        )
    except subprocess.CalledProcessError:
        return set()

    symbols = set()
    for line in output.splitlines():
        parts = line.split()
        if not parts:
            continue
        name = parts[-1]
        if "@" in name:
            name = name.split("@", 1)[0]
        symbols.add(name)
    return symbols


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--syslib-root", required=True)
    parser.add_argument("--apis", required=True, nargs="+")
    parser.add_argument("--nm", required=True)
    parser.add_argument("--required", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    required = parse_required(args.required)
    candidates = {sym: set() for syms in required.values() for sym in syms}

    for api in args.apis:
        for lib, symbols in required.items():
            so_path = os.path.join(args.syslib_root, f"android-{api}", "lib64", f"{lib}.so")
            if not os.path.exists(so_path):
                continue
            exports = nm_symbols(args.nm, so_path)
            for sym in symbols:
                if sym in exports:
                    candidates[sym].add(sym)

    for sym in list(candidates.keys()):
        if not candidates[sym]:
            candidates[sym].add(sym)

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("#pragma once\n\n")
        f.write("// Auto-generated by CI. Do not edit by hand.\n\n")
        for sym in sorted(candidates.keys()):
            names = sorted(candidates[sym])
            arr = ", ".join([f"\"{n}\"" for n in names])
            f.write(f"static const char* kCandidates_{sym}[] = {{{arr}}};\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
